### ISSUE TITLE
Add compatibility fir latest releaseasw0.96

### ISSUE THREAD

**Issue by thundergreen** [Anonym-tsk/home-assistant-components#14]
Hi unfortunately there was a rewrite of the climate component and this custom component doesn't work anymore ..is it possible to adjust it?

Thanks in advance

**Comment by mokshmridul** [comment]
Yes, comparability seems to be broken after the 0.96.0 release.

**Comment by Anonym-tsk** [comment]
Please update component.
Also, your config must be updated:
`operation_mode` -> `hvac_mode`
`operation_list` -> `hvac_modes`
`fan_list` -> `fan_modes`

**Comment by thundergreen** [comment]
thanks worked :)
