### ISSUE TITLE
Restore state doesn't work

### ISSUE THREAD

**Issue by CooleRnax** [Anonym-tsk/home-assistant-components#7]
When I restart home assistant. If ac is turned off, it will become on after reboot.

**Comment by Anonym-tsk** [comment]
Please update component and try again

**Comment by CooleRnax** [comment]
i already have the latest version

**Comment by CooleRnax** [comment]
btw I have no sensor to check if it is on or off

**Comment by Anonym-tsk** [comment]
@CooleRnax please update component again
